<template>
	<section class="auth">
		<div class="container">
			<div class="back">
				<RouterLink to="/landing"> <fa icon="arrow-left-long" class="text-white" /></RouterLink>
			</div>
			<h1 class="title mb-4" style="font-size: 30px">Create an Account</h1>
			<!-- <small class="d-block mb-4">My <span class="highlight">Vibe</span></small> -->
			<form autocomplete="off" @submit.prevent="register">
				<div class="mb-3">
					<label class="form-label">Username</label>
					<input type="text" class="form-control" v-model="username" placeholder="Type your username here" required />
				</div>
				<div class="mb-3">
					<label class="form-label">Name</label>
					<input type="text" class="form-control" v-model="name" placeholder="Type your name here" required />
				</div>
				<div class="mb-3">
					<label class="form-label">Email</label>
					<input type="email" class="form-control" v-model="email" placeholder="Type your email address here" required />
				</div>
				<div class="mb-3">
					<label class="form-label">Password</label>
					<input type="password" class="form-control" v-model="password" placeholder="Make a strong password" required />
				</div>
				<div class="mb-3">
					<label class="form-label">Password Confirmation</label>
					<input type="password" class="form-control" v-model="repassword" placeholder="Retype a strong password" required />
				</div>
				<div class="d-flex justify-content-center align-items-center flex-column mt-4 gap-2">
					<div class="form-check" data-bs-toggle="modal" data-bs-target="#termsModal">
						<input class="form-check-input" type="checkbox" v-model="isChecked" :disabled="!isCheckboxEnabled" />
						<label class="form-check-label" for="flexCheckDefault">Agree to MyVibe Planner’s Terms of Use</label>
					</div>
					<button type="submit" class="btn-action" :disabled="!isChecked">
						<span v-if="!loading" class="me-2">Register Now!</span>
						<span v-else> <fa icon="spinner" class="fa-spin" /> Loading... </span>
					</button>
				</div>
			</form>
		</div>
		<span data-bs-toggle="modal" data-bs-target="#notifModal" ref="notifModalBtn"></span>
		<div class="modal fade" id="termsModal" tabindex="-1" aria-labelledby="termsModalLabel" aria-hidden="true">
			<div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
				<div class="modal-content">
					<div class="modal-body" style="height: 50vh" ref="termsContent" @scroll="checkScroll">
						<h2>General Terms</h2>
						<p>Updated at January 18th, 2025</p>
						<p>By accessing and placing an order with MyVibe, you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and MyVibe.</p>
						<p>Under no circumstances shall MyVibe team be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if MyVibe team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair or correction of equipment or data, you assume any costs thereof.</p>
						<p>MyVibe will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the rights to change prices and revise the resources usage policy in any moment.</p>

						<h2>License</h2>
						<p>MyVibe grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the app strictly in accordance with the terms of this Agreement.</p>
						<p>These Terms & Conditions are a contract between you and MyVibe (referred to in these Terms & Conditions as "MyVibe", "us", "we" or "our"), the provider of the MyVibe website and the services accessible from the MyVibe website (which are collectively referred to in these Terms & Conditions as the "MyVibe Service").</p>
						<p>You are agreeing to be bound by these Terms & Conditions. If you do not agree to these Terms & Conditions, please do not use the MyVibe Service. In these Terms & Conditions, "you" refers both to you as an individual and to the entity you represent. If you violate any of these Terms & Conditions, we reserve the right to cancel your account or block access to your account without notice.</p>

						<h2>Definitions and Key Terms</h2>
						<p>To help explain things as clearly as possible in this Terms & Conditions, every time any of these terms are referenced, are strictly defined as:</p>
						<ul>
							<li><strong>Cookie:</strong> A small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
							<li><strong>Company:</strong> When this terms mention “Company,” “we,” “us,” or “our,” it refers to MyVibe, that is responsible for your information under this Terms & Conditions.</li>
							<li><strong>Country:</strong> Where MyVibe or the owners/founders of MyVibe are based, in this case is Indonesia</li>
							<li><strong>Device:</strong> Any internet connected device such as a phone, tablet, computer or any other device that can be used to visit MyVibe and use the services.</li>
							<li><strong>Service:</strong> Refers to the service provided by MyVibe as described in the relative terms (if available) and on this platform.</li>
							<li><strong>Third-party service:</strong> Refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
							<li><strong>App/Application:</strong> MyVibe app, refers to the SOFTWARE PRODUCT identified above.</li>
							<li><strong>You:</strong> A person or entity that is registered with MyVibe to use the Services.</li>
						</ul>

						<h2>Restrictions</h2>
						<p>You agree not to, and will not permit others to:</p>
						<ul>
							<li>License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the app or make the platform available to any third party.</li>
							<li>Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the app.</li>
							<li>Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of MyVibe or its affiliates, partners, suppliers or the licensors of the app.</li>
						</ul>

						<h2>Return and Refund Policy</h2>
						<p>If you are not satisfied with any product or service, contact us to discuss your concerns.</p>

						<h2>Your Suggestions</h2>
						<p>Suggestions provided to MyVibe remain the sole property of MyVibe.</p>

						<h2>Contact Us</h2>
						<p>If you have any questions:</p>
						<ul>
							<li>Email: <a href="mailto:lukersaintfeller@gmail.com">lukersaintfeller@gmail.com</a></li>
							<li>Phone: +6282278709681</li>
						</ul>
					</div>
					<div class="modal-button">
						<button type="button" class="btn-block" data-bs-dismiss="modal" @click="confirmClick" aria-label="Close">Close</button>
					</div>
				</div>
			</div>
		</div>
		<div class="modal fade" id="notifModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="notifModalLabel" aria-hidden="true">
			<div class="modal-dialog modal-dialog-centered">
				<div class="modal-content">
					<div class="modal-body notification">
						<div class="title">
							<h1>
								{{ titleNotif }} <span :class="{ success: statusNotif === 'success' }">{{ titleNotifSecond }}</span>
							</h1>
						</div>
						<p class="m-0 text-center">{{ message }}</p>
					</div>
					<div class="modal-button" v-if="showLink">
						<RouterLink :to="linkTo" class="btn-block purple" @click="clickLink"> {{ linkText }} </RouterLink>
					</div>
					<div class="modal-button" v-if="showDismiss">
						<button type="button" class="btn-block" data-bs-dismiss="modal" aria-label="Close">Close</button>
					</div>
				</div>
			</div>
		</div>
	</section>
</template>

<script>
import 'bootstrap/dist/js/bootstrap.bundle.min.js';

import authService from '@/services/authService';

export default {
	name: 'RegisterView',
	data() {
		return {
			username: '',
			name: '',
			email: '',
			password: '',
			repassword: '',
			loading: false,
			statusNotif: 'failed',
			titleNotif: '',
			titleNotifSecond: '',
			message: '',
			showLink: false,
			linkTo: '/',
			linkText: 'Okay',
			showDismiss: false,
			isCheckboxEnabled: false,
			isChecked: false
		};
	},
	mounted() {},
	methods: {
		async register() {
			this.loading = true;
			try {
				const response = await authService.register({
					username: this.username,
					name: this.name,
					email: this.email,
					password: this.password,
					password_confirmation: this.repassword
				});
				this.statusNotif = 'success';
				this.titleNotif = 'Registration';
				this.titleNotifSecond = 'Success!';
				this.message = response.data.message;
				this.showLink = true;
				this.showDismiss = false;
				this.linkTo = '/login';
				this.showNotifModal();
			} catch (error) {
				this.statusNotif = 'failed';
				this.titleNotif = 'Registration';
				this.titleNotifSecond = 'Failed';
				this.message = error.response.data.message;
				this.showLink = false;
				this.showDismiss = true;
				this.linkTo = '';
				this.showNotifModal();
			} finally {
				this.loading = false;
			}
		},
		checkScroll() {
			const termsContent = this.$refs.termsContent;
			if (termsContent.scrollTop + termsContent.clientHeight >= termsContent.scrollHeight) {
				this.isCheckboxEnabled = true;
				this.isChecked = true;
			}
		},
		confirmClick() {
			this.isCheckboxEnabled = true;
			this.isChecked = true;
		},
		clickLink() {
			var backdrop = document.querySelector('.modal-backdrop');
			if (backdrop) {
				backdrop.remove();
			}
		},
		showNotifModal() {
			this.$refs.notifModalBtn.click();
		}
	}
};
</script>
